### ISSUE TITLE
Visibility: Hidden Instead of Display: None

### ISSUE THREAD

**Issue by hew** [souporserious/react-view-pager#11]
`lib/slide.js`

![](http://f.cl.ly/items/1g2S2j0G2t3h1K0d1o0J/Image%202016-02-11%20at%201.11.15%20PM.png)

I suggest changing this from `display: none` to `visibility: hidden` 

As you allude to in your comment, `display: none` takes the element out of the entire document flow, and on the initial render prevents proper DOM calculation. However, `display: none` also blocks any animation from occurring, and the potential to animate the slider would be nice.

**Comment by souporserious** [comment]
Not sure what you mean, is something not working for you? The slider animates the slides horizontally and vertically. This is going through a heavy re-work though so I'm closing this for now.
