### ISSUE TITLE
Ability to "show a little of the next/prior slide"?

### ISSUE THREAD

**Issue by cymen** [souporserious/react-view-pager#19]
I have a requirement where basically you can tell there are more slides to left or right because you see a the edge of the next/prior slide. I'm figuring out if there is a way to do that right now but figured I'd ask too. I'll update if I figure it out. Thanks!

**Comment by souporserious** [comment]
That can be achieved with CSS by adjusting your wrapping element. So there are `.slider` and `.slider__track` classes. If you adjust the `.slider`'s padding it will show peeking of the next/prev slides. You can see it in use here https://flassh.co/ at the bottom of the page.

**Comment by cymen** [comment]
@souporserious Awesome! That saves me a lot of time. Thanks so much.
