### ISSUE TITLE
Inline/Radium Styles?

### ISSUE THREAD

**Issue by iDVB** [souporserious/react-view-pager#22]
The root component does not seem to have propagated the **style** property. Seems like because of this we'd have to use CSS in order to use this module?

**Comment by souporserious** [comment]
Sorry about that. I wrote this when I was first learning React. I'm busy right now, but please feel free to make a PR :)

**Comment by casesandberg** [comment]
@iDVB what type of behaviour would you like to happen?

**Comment by souporserious** [comment]
@iDVB almost done with a rewrite that will allow you access to each component so you can pass in whatever you want :) [see here](https://github.com/souporserious/react-motion-slider/tree/rewrite-round-three#example-usage)

**Comment by efflam** [comment]
soupornice !
I use glamor for styles so that will be exactly what i need. Thx !

**Comment by souporserious** [comment]
I released a prerelease version. Go get your inline styles on 💃  please let me know if you find any bugs.
