### ISSUE TITLE
polylinearScale is not defined

### ISSUE THREAD

**Issue by efflam** [souporserious/react-view-pager#27]
Hi !
I've updated react-view-pager and I got this error at runtime
Uncaught ReferenceError: polylinearScale is not defined

**Comment by souporserious** [comment]
Oh no :( sorry about that. I will look into it this morning and see what's wrong.

**Comment by souporserious** [comment]
What environment are you running this in? Maybe you are missing this dependency of animation-bus https://github.com/souporserious/animation-bus/blob/master/package.json#L35

**Comment by efflam** [comment]
Node 7.1.0
Bundled with webpack.
I don't use yarn for now.
I've tried to  install animation-bus and polylinear-scale separately but it doesn't solve the problem.
But the function is clearly here...
![capture d ecran 2016-11-22 a 11 32 51](https://cloud.githubusercontent.com/assets/149307/20520524/7ae3de82-b0a7-11e6-93cd-94dd4b4c667c.png)

**Comment by efflam** [comment]
Other people don't seem to have this problem so it's clearly something with my config but it's just create-react-app...

**Comment by souporserious** [comment]
So weird, I wish I knew more to help 😕 have you tried removing `node_modules` and reinstalling?

**Comment by efflam** [comment]
In fact, it seems to be a Chrome problem: Version 54.0.2840.98 (64-bit)
It's running fine with Canary : Version 57.0.2926.0 canary (64-bit) and Safari...

**Comment by souporserious** [comment]
Interesting 🤔  I'm on the same version and have not experienced any issues. You think this ok to close? Seems very specific.

**Comment by efflam** [comment]
yes, no problem to close ;) very specific indeed (maybe a problem with a chrome extension, i don't know...)
