### ISSUE TITLE
Frame's `align` prop

### ISSUE THREAD

**Issue by azangru** [souporserious/react-view-pager#30]
The docs [say](https://github.com/souporserious/react-view-pager#align-proptypesoneofleft-center-right) that the `align` prop of the Frame component is a string of one of three types, but the component itself [expects a number](https://github.com/souporserious/react-view-pager/blob/master/src/Frame.jsx#L17) (which can be 0, 0.5 or 1).

**Comment by souporserious** [comment]
Sorry about that! The docs now reflect the new align prop.
