### ISSUE TITLE
project renamed?

### ISSUE THREAD

**Issue by bnhovde** [souporserious/react-view-pager#33]
Hi,

Thanks for creating this library, works great.

Looks like the project has changed names, along with the imports and how the components are structured? Just wondering what the process is for upgrading, am I best off just scrapping the old code and grabbing a new copy?

Cheers!

**Comment by souporserious** [comment]
Thanks for the kind words! I'm glad you like it. Sorry about the API change, I wanted to allow the library to be composed with other components easier so it required some abstracting. The dust has finally settled though and I don't foresee any major API changes. Please see the [CHANGELOG](https://github.com/souporserious/react-view-pager/blob/master/CHANGELOG.md) for more info on upgrading. You can check the examples folder as well to see how I upgraded examples. Or if you run into a snag just hit me up and I'll do my best to help you transition.

**Comment by bnhovde** [comment]
Great! Thanks mate, should have checked the changelog.

Keep up the good work!
