### ISSUE TITLE
this._pager.destroy is not a function

### ISSUE THREAD

**Issue by efflam** [souporserious/react-view-pager#40]
Hello,
It seems that the destroy method on the Pager class doesn't exist causing a error on componentWillUnmount.

**Comment by souporserious** [comment]
Apologies! That's what I get for writing code when I should be sleeping 😴  It has been fixed [here](https://github.com/souporserious/react-view-pager/commit/06c5b9d6730c4c496f41c3e5b45b15bda4e798fa) and is available in the latest release.

**Comment by efflam** [comment]
Yeah ! Have some rest now ;) Thx!
