### ISSUE TITLE
ResizeObserver is not constructor

### ISSUE THREAD

**Issue by primozs** [souporserious/react-view-pager#48]
In Pager.js this should be like this: Note .default
```
if (isWindowDefined && !window.ResizeObserver) {
  window.ResizeObserver = require('resize-observer-polyfill').default;
}
```
Or it should be build with this. I think.
https://github.com/59naga/babel-plugin-add-module-exports
Cheers

**Comment by primozs** [comment]
Hm, It seams I have an issue when I build this with webpack2.

**Comment by souporserious** [comment]
Sorry about that, had some hiccups switching to using a ResizeObserver. Should be fixed here https://github.com/souporserious/react-view-pager/commit/586eb9a2d64a35931c5774a37b2ab7da4f4d3885 and is out in the latest prerelease. Please feel free to re-open this if it doesn't fix your issue.

**Comment by primozs** [comment]
Thx, this is really nice component!
Cheers
