### ISSUE TITLE
The lib folder wasn't there after npm install react-motion-slider

### ISSUE THREAD

**Issue by oliviertassinari** [souporserious/react-view-pager#5]
I don't know why, the `package.json` scripts desction looks ok.

**Comment by souporserious** [comment]
Did you ever figure this out? It's seems to be working fine on my end.

**Comment by oliviertassinari** [comment]
Yes. you need an `npmignore` for instance https://github.com/oliviertassinari/react-swipeable-views/blob/master/.npmignore. Otherwise, npm use the .gitignore.

**Comment by souporserious** [comment]
Added `.npmignore` in this commit https://github.com/souporserious/react-motion-slider/commit/d26f4edea5a60d24528c285ff4c787f24f45bd2f it's not included in Github that should fine right?

**Comment by oliviertassinari** [comment]
I couldn't test. As you have seen, I ended up building my own slider solution.

**Comment by souporserious** [comment]
To get the lib folder, you need to run `npm run build`. I did see that, good stuff! :)
