### ISSUE TITLE
0.5.0-prerelease.9  can not resolve module 'react-view-pager'

### ISSUE THREAD

**Issue by disoul** [souporserious/react-view-pager#54]
can not find `lib`  in this module

**Comment by LeoIannacone** [comment]
Confirmed

**Comment by davthu** [comment]
Confirmed. Rolled back to prerelease 8 and it works again.

**Comment by souporserious** [comment]
So sorry about that! I'm wondering if it was something from `yarn publish` :( Can you please try `0.5.0-prerelease.10`? I published that one with `npm publish`.

**Comment by LeoIannacone** [comment]
Worked for me, thanks!

**Comment by souporserious** [comment]
Awesome 🎉  closing this. Please feel free to re-open if it's still not loading properly.
