### ISSUE TITLE
Support for react v16

### ISSUE THREAD

**Issue by ghost** [souporserious/react-view-pager#67]
Upgrading react and react-dom to `v16.0.0` gets following error:

```
Module not found: Error: Can't resolve 'react/lib/React' in '/app/node_modules/react-view-pager/node_modules/react-dom/lib'
```

**Comment by jeremyrajan** [comment]
@msmfsd see if this helps? :)

https://github.com/souporserious/react-view-pager/pull/69

**Comment by ghost** [comment]
@jeremyrajan thanks!

**Comment by souporserious** [comment]
Sorry for the wait on this. It should be fixed now https://github.com/souporserious/react-view-pager/commit/19d86cfad96081b7d014b6642fa21d76e3e08dab
