### ISSUE TITLE
The animation does not work properly.

### ISSUE THREAD

**Issue by gavin1995** [souporserious/react-view-pager#68]
![2017-10-27 09 38 08](https://user-images.githubusercontent.com/26155356/32084277-b82f0f32-ba8d-11e7-87db-a82f89ea5f66.gif)

Obviously, did not get the right result.

The middle card should not be scaled.

Core code:

    import React, { Component } from 'react';
    import { ViewPager, Frame, Track, View } from 'react-view-pager'
    
    const animations = [
      {
        prop: 'scale',
        stops: [
          [-50, 0.8],
          [0, 1],
          [50, 0.8]
        ]
      },
    ]
    export default class Snap extends Component {
      render() {
        return (
          <ViewPager>
            <Frame>
              <Track
                viewsToShow={2}
                // infinite={true}
                align={0.5}
                animations={animations}
              >
                <View>
                  <div className="card">1</div>
                </View>
                <View>
                  <div className="card">2</div>
                </View>
                <View>
                  <div className="card">3</div>
                </View>
                <View>
                  <div className="card">4</div>
                </View>
                <View>
                  <div className="card">5</div>
                </View>
                <View>
                  <div className="card">6</div>
                </View>
                <View>
                  <div className="card">7</div>
                </View>
              </Track>
            </Frame>
            {/*language=CSS*/}
            <style jsx>{`
              .card {
                  width: 570px;
                  height: 490px;
                  background-color: #d24747;
              }
            `}</style>
          </ViewPager>
        );
      }
    }
    
package.json

    "next": "4.1.0", // I use server-side rendering
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-view-pager": "^0.5.1",
    
Thank you!

**Comment by gavin1995** [comment]
Add

    _handleScroll = (progress, trackPosition) => {
        this.setState({ progress })
    }

**Comment by kristojorg** [comment]
Hi @Gavin1995 can you elaborate on your solution to this? I think I am experiencing the same issue
