### ISSUE TITLE
use of document in getPrefix.js breaks server-side rendering

### ISSUE THREAD

**Issue by efflam** [souporserious/react-view-pager#7]
Hi, 
I'm to trying to use your slider in an app based on https://github.com/erikras/react-redux-universal-hot-example but `document` in `getPrefix.js` breaks server-side rendering.

**Comment by souporserious** [comment]
Is there a way I can check against this and not use it if it's being used server side? Maybe I'll just leave it up to the user to handle prefixing.

**Comment by efflam** [comment]
Do you think there is a performance cost by setting all prefixed transforms even if they aren't actually needed by the user's browser ?
If not, maybe just remove getPrefix.js and doing like so in Slide.js can be enough: 

```
style.transform = style.WebkitTransform =  `translate3d(${translateX}%, 0, 0)`
```

**Comment by souporserious** [comment]
Fixed https://github.com/souporserious/react-motion-slider/commit/adc013ed984af7345c53e85c40632c8b884e5a75
